message=Hello Jag from Service A
service.a.datasource.url=jdbc:mysql://localhost:3306/service_a_db
service.a.datasource.username=service_a_user
service.a.datasource.password=secret123
timeout.seconds=10
